apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: cert-manager
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: mirioeggmann/cloudflare-ddns:latest
              env:
              - name: ZONE_ID
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-dns-secret
                    key: dns-root-zoneId
              - name: RECORD_ID
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-dns-secret
                    key: dns-root-recordId
              - name: API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-dns-secret
                    key: api-token
              - name: NAME
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-dns-secret
                    key: dns-root-name
              - name: PROXIED
                value: "false"
          restartPolicy: OnFailure
